### ISSUE TITLE
Convention / Standard for messages

### ISSUE THREAD

**Issue by Ze-Rax** [Ze-Rax/TrackmaniaFlagRush#181]
All messages (BigMessages, Event feed messages, ...) should be consistent in terms of writing an punctuation. We should have some kind of standard / convention for that.

**Comment by Geekid812** [comment]
Just to mention, this was previously brought up in #176 and in #83, there is relevant discussion in these PRs.

So far, we have used the same punctation convention between BigMessages and Event Feed messages. Usually, there is a `declare Message` which is commonly sent to both ClientUI and EventFeed. I don't think this behaviour needs to be changed. Since it is so common, it could even be merged into a helper function (`FlagRush_UI::Broadcast()` for example).

What is subject to change is the punctation depending on each message's type. For most of the messages we have, I always had in mind that they should be written as if a caster would have said it: "X got the flag!" "The flag was reset!" "X seconds remaining!". The only exception that we currently have is Round Start, Warmups and Overtime. I actually changed my mind and now think they should stay as exceptions which could be grouped under a "Phase Change" category where no punctuation is used.

Concerning the colors, messages are currently correctly colored in my opinion. The general rule should be that player names are colored with their team names, and warmup and time messages should be orange.

**Comment by Geekid812** [comment]
Adding to this (as i accidentally submitted the comment early), the current exception to that rule currently is that the flag get message also colors the "flag" word with the team name. This exception could be fine to keep, as it indicates that the flag switched teams.
